# Generated by Django 4.2.10 on 2024-02-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['id']},
        ),
    ]
